
ctx:                        'Training with Sigmoid Act'

epoch:                      20

ace:
  seq_len:                  10
  hiddenSize1:              5
  hiddenSize2:              2
  train_per:                0.8
  LR:                       0.001
  sensor_spec_loss:         True
  corr_loss:                True

testSize:                   200

dataset:
  regexp_bin:               ''
  regexp_sensor:            ''
  impute_anomaly:           True
