
ctx:                        'Description of the state'

epoch:                      10

ace:
  seq_len:                  100
  hiddenSize1:              5
  hiddenSize2:              5
  train_per:                0.8
  LR:                       0.001

testSize:                   60000

dataset:
  regexp_bin:               ''
  regexp_sensor:            ''
  impute_anomaly:           True
