
ctx:                        'Training with Sigmoid Act'

epoch:                      10

ace:
  seq_len:                  100
  hiddenSize1:              5
  hiddenSize2:              5
  train_per:                0.7
  LR:                       0.001
  sensor_spec_loss:         True
  corr_loss:                True

testSize:                   30000

dataset:
  regexp_bin:               ''
  regexp_sensor:            ''
  impute_anomaly:           True

