
ctx:                            'Load_F2_F3'

epoch:                          2

isTraining:                     True

ace:
    seq_len:                    100
    hiddenSize1:                5
    hiddenSize2:                5
    train_per:                  1
    train_max:                  0.01
    LR:                         0.001
    sensor_spec_loss:           True
    corr_loss:                  True
    num_error_vects:            Null
    #load_file:                  Null
    load_file:                  ['results/AutoencoderJO_[F2]',
                                'results/AutoencoderJO_[F2]']
    #load_file:                  ['results/AutoencoderJO_[N.*_F3.*SG_2_N.*, N.*_F3.*SG_2_SO.*]',
    #                           'results/AutoencoderJO_[N.*_F2.*SG_2_N.*]']

testSize:                       10000

dataset:
    data_dir:                   '/osimab/data/itc-prod2.com/'
    #regexp_bin_train:           ['OSIMAB_2020_08_20_0[3-4]*.zip', 'OSIMAB_2020_08_21_0[2-4]*.zip']
    regexp_bin_train:           ['OSIMAB_2020_08_20_0[3-4]*.zip']
    regexp_bin_test:            ['OSIMAB_2020_08_20_0[2]*.zip']
    regexp_sensor:              ['F3']
    #regexp_sensor:              ['N.*_F3.*SG_2_N.*', 'N.*_F3.*SG_2_SO.*']
    #regexp_sensor:              ['N.*_F2.*SG_2_N.*']
    #regexp_sensor:              ['.*']
    #impute_anomaly:             True
    anomalies:                  Null
    #        nullSensor:             1
    #        shift:                  1
    #        variance:               1
    #        peak:                   1
    #        timeshift:              0
    #        trend:                  0
