
#ctx:                            'NoCorr_Loss_SameError_Loss_MSE_SensorSpec_noPeak'
ctx:                            'MultipleSG_NoAnomalies_TrainRHStoo_summedrhs_linear_tradeoff'

epoch:                          20

isTraining:                     True

ace:
    seq_len:                    100
    hiddenSize1:                5
    hiddenSize2:                5
    train_per:                  1
    train_max:                  0.01
    LR:                         0.001
    sensor_spec_loss:           True
    corr_loss:                  True
    warm_start:                 False

testSize:                       10000

dataset:
    #regexp_bin:                 ['OSIMAB_2020_06_26_0[2]*.zip']
    data_dir:                   '/osimab/data/itc-prod2.com/'
    regexp_bin_train:           ['OSIMAB_2020_08_20_0[2-5]*.zip']
    #regexp_sensor:              ['N.*_F3.*INC_1.*']
    regexp_sensor:              ['N.*_F3.*SG_2_N.*', 'N.*_F3.*SG_2_SO.*']
    #regexp_sensor:              ['.*']
    #impute_anomaly:             True
    anomalies:                  #Null
        nullSensor:             1
    #        shift:                  1
    #        variance:               1
    #        peak:                   1
    #        timeshift:              0
    #        trend:                  0
