
ctx:                            'CodeTest'

epoch:                          2

isTraining:                     True

ace:
    seq_len:                    100
    hiddenSize1:                5
    hiddenSize2:                5
    train_per:                  1
    train_max:                  0.01
    LR:                         0.001
    sensor_spec_loss:           True
    corr_loss:                  True
    warm_start:                 False

testSize:                       30000

dataset:
    #regexp_bin:                 ['OSIMAB_2020_06_26_0[2]*.zip']
    data_dir:                   '/osimab/data/itc-prod2.com/'
    regexp_bin_train:           ['OSIMAB_2020_08_20_0[2]*.zip']
    regexp_sensor:              ['N.*_F3.*ACC.*']
    #regexp_sensor:              ['.*']
    #impute_anomaly:             True
    anomalies:                  #Null
        shift:                  1
        variance:               2
        peak:                   1
        timeshift:              2
        trend:                  1
