ctx:                            'TrainEntireSmallLSTMED'

modeFlg:                        ['both'] # {'train', 'test', 'both'}

epoch:                          10
log_file:                       False


#ace:
model:
    type:                       ['ace'] # {'ace', 'lstmed'}
    # both
    seq_len:                    100
    #train_per:                  1
    details:                    True
    LR:                         0.001
    train_max:                  1 # {1, 0.02}
    load_file:                  [
                                'results/model_AutoencoderJO_entireSmallDataset'
                                ]
    # ace
    hiddenSize1:                5
    hiddenSize2:                5
    aggr_func:                  'xor'
    sensor_spec_loss:           True
    corr_loss:                  True
    #num_error_vects:            Null
    # lstmed
    hiddenSize:                 110


datasets:
    trainSmall:                 False
    data_dir:                   '/osimab/data/itc-prod2.com/'
    regexp_bin_train:           Null
    regexp_bin_test:            Null
    testSize:                   10000
    regexp_sensor:              ['.*']
    anomalies:
        nullSensor:             1
        shift:                  1
        variance:               1
        peak:                   1
        timeshift:              1
        trend:                  1
    anomalies:                  Null
